services:
    recipe-backend:
        build:
            context: .
            args:
                - DEV=true
            dockerfile: Dockerfile
        container_name: django-recipe-app
        ports:
        - '${APP_PORT}:${APP_PORT}'
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: '${DB_PORT}'
            DB_NAME: '${DB_NAME}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            recipe-db:
                condition: service_healthy
        restart: unless-stopped
        read_only: true
        networks:
        - app-recipe-net
        volumes:
          - ${PWD}:/app
        mem_limit: 515M
        cpus: '0.5'
        command: >
            sh -c "
                python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000
            "

    recipe-db:
        image: postgres:18-alpine
        container_name: app-recipe-db
        environment:
            POSTGRES_DB: '${DB_NAME}'
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
        - app-recipe-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
        - app-recipe-net
        mem_limit: 515M
        cpus: '0.5'

volumes:
  app-recipe-data:

networks:
  app-recipe-net: